name: Publicar Documentação Swagger

on:
  push:
    branches:
      - main  # Ou a branch que deseja usar

permissions:
  contents: write  # Permissão para escrever no repositório
  pages: write     # Permissão para publicar no GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 📦 Configurar Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs  # Diretório onde a documentação será gerada
          spec-file: openapi.yaml  # Arquivo OpenAPI/YAML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Adicionando o token

      - name: 🚀 Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          token: ${{ secrets.GITHUB_TOKEN }}  # Adicionando o token aqui também
